# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

language: node_js

node_js:
  - 10
  - 8
  - 6

os:
  - linux
  - osx
  - windows

matrix:
  include:
    - name: Browser tests (Linux)
      os: linux
      node_js: 10
      env: BROWSER_TESTS=true
      addons:
        firefox: latest
        chrome: stable

    - name: Browser tests (Mac)
      os: osx
      node_js: 10
      env: BROWSER_TESTS=true
      addons:
        firefox: latest
        chrome: stable

    - name: Browser tests (Windows via SauceLabs)
      os: linux
      node_js: 10
      env:
        - BROWSER_TESTS=true
        - WINDOWS=true

before_script:
  # Link the package to itself (so Karma and Mocha can find it)
  - npm link
  - npm link karma-host-environment

script:
  - npm run lint
  - npm run coverage

script:
  if [ ${BROWSER_TESTS} = "true" ]; then
    npm run coverage:browser;
  else
    npm run lint;
    npm run coverage:node;
    npm run test:typescript;
  fi

after_success:
  # concatenate all code-coverage data into a single file
  - ls -R1 coverage/*/lcov.info
  - cat coverage/*/lcov.info > ./coverage/lcov.info

  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | coveralls
